version: 3

dotenv:
  - .secrets/env

vars:
  Varsfile: ".secrets/varfile.json"

tasks:
  init:
    cmds:
      - terraform init
    silent: true

  plan:
    dir: ./
    vars:
      PlanOutput: ".secrets/plan.out"
    cmds:
      - terraform plan 
        --var aws_access_key=${AWS_ACCESS_KEY_ID}
        --var aws_secret_key=${AWS_SECRET_ACCESS_KEY}
        --var cloudflare_api_token=${CLOUDFLARE_API_TOKEN}
        --var cloudflare_zone_id=${CLOUDFLARE_ZONE_ID}
        --var cloudflare_domain=${CLOUDFLARE_DOMAIN}
        --out "{{.PlanOutput}}"

  apply:
    dir: ./
    dotenv:
      - .secrets/env
    vars:
      PlanOutput: ".secrets/plan.out"
    cmds:
      - terraform apply "{{.PlanOutput}}"

  validate:
    dir: ./
    cmds:
      - terraform validate  -var-file=vars.auto.tfvars

  destroy:
    dir: ./
    dotenv:
      - .secrets/env
    vars:
      PlanOutput: ".secrets/plan.destroy.out"
    cmds:
      - terraform plan
          --var aws_access_key=${AWS_ACCESS_KEY_ID}
          --var aws_secret_key=${AWS_SECRET_ACCESS_KEY}
          --var cloudflare_api_token=${CLOUDFLARE_API_TOKEN}
          --var cloudflare_zone_id=${CLOUDFLARE_ZONE_ID}
          --var cloudflare_domain=${CLOUDFLARE_DOMAIN}
          --destroy
          --out "{{.PlanOutput}}"
      - terraform apply "{{.PlanOutput}}"
