FROM ubuntu:24.04

# Update and install necessary dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user 'kl'
RUN useradd -m -s /bin/bash -u 1001 kl

RUN mkdir /venv

RUN chown -R kl:kl /venv
# Create a virtual environment and install Jupyter Notebook as 'kl'
USER kl

RUN python3 -m venv /venv && \
    /venv/bin/pip install --no-cache-dir jupyter

# Expose the Jupyter port
EXPOSE 8888

# Command to start Jupyter Notebook
CMD ["/venv/bin/jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.password=''"]
