FROM ubuntu:24.04

RUN apt update && apt install -y curl

RUN curl -fsSL https://code-server.dev/install.sh | sh

RUN useradd -m -s /bin/bash -u 1001 kl

USER kl

CMD ["code-server", "--auth", "none"]