#syntax=docker/dockerfile:1
FROM gcr.io/distroless/static-debian11:nonroot
LABEL org.opencontainers.image.source https://github.com/kloudlite/infrastructure-as-code
WORKDIR /app
COPY --chown=1001 ./app ./app
CMD ["./app"]
ENTRYPOINT ["./app"]