apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-web-service
spec:
  selector:
    matchLabels:
      app: code-web-service
  template:
    metadata:
      labels:
        app: code-web-service
    spec:
      nodeSelector:
        kloudlite.io/node.role: worker
      initContainers:
        - name: init-home-dir
          image: busybox
          command: ["sh", "-c", "chown -R 1001:1001 /var/user-home"]
          volumeMounts:
            - mountPath: /var/user-home
              name: home-dir
      containers:
      - name: ssh
        image: ghcr.io/kloudlite/iac/workspace:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 22
        volumeMounts:
          - mountPath: /home/kl
            name: home-dir
      - name: jupyter
        image: ghcr.io/kloudlite/iac/jupyter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        volumeMounts:
          - mountPath: /home/kl
            name: home-dir
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
      - name: vscode-server
        image: ghcr.io/kloudlite/iac/vscode-server:latest
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /home/kl
            name: home-dir
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
      - name: code-server
        image: ghcr.io/kloudlite/iac/code-server:latest
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /home/kl
            name: home-dir
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001

      volumes:
      - name: home-dir
        hostPath:
          path: /var/user-home

---

apiVersion: v1
kind: Pod
metadata:
  name: exposed-services
spec:
  containers:
  - name: exposed-services
    image: busybox:latest
    imagePullPolicy: Always
    command:
      - sh
      - -c
      - |
  nodeSelector:
    kloudlite.io/node.role: worker
