apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-web-service
spec:
  selector:
    matchLabels:
      app: code-web-service
  template:
    metadata:
      labels:
        app: code-web-service
    spec:
      tolerations:
        - key: "kloudlite.io/worknode"
          operator: "Equal"
          value: "node1"
          effect: "NoExecute"
      nodeSelector:
        kloudlite.io/node.role: worker
      initContainers:
        - name: init-home-dir
          image: ghcr.io/kloudlite/iac/workspace:latest
          env:
            - name: KL_WORKSPACE
              value: "workspaces/ws-name"
            - name: HOME
              value: "/home/kl"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          command:
          - "bash"
          - "-c"
          - |
            set -e
            ls /tmp
            if [ ! -d "/nix/store" ]; then
              curl -L https://nixos.org/nix/install | sh
              mkdir -p ~/.config/nix
              echo 'experimental-features = nix-command flakes' > ~/.config/nix/nix.conf
            fi

            if [ ! -d "/home/kl/$(KL_WORKSPACE)" ]; then
              mkdir -p /home/kl/$(KL_WORKSPACE)
            fi

            if [ ! -f "/home/kl/.local/bin/kl" ]; then
                  mkdir -p /home/kl/.local/bin
                  cd /home/kl/.local/bin
                  curl https://i.jpillora.com/kloudlite/kl@1.1.71-nightly | bash
            fi

            if [ ! -d "/home/kl/.config/zsh/pure" ]; then
              mkdir -p "/home/kl/.config/zsh"
              git clone https://github.com/sindresorhus/pure.git "/home/kl/.config/zsh/pure"
            fi

            if [ ! -d "/home/kl/.config/zsh/zsh-syntax-highlighting" ]; then
              mkdir -p "/home/kl/.config/zsh"
              git clone https://github.com/zsh-users/zsh-syntax-highlighting.git  "/home/kl/.config/zsh/zsh-syntax-highlighting"
            fi

            if [ ! -f "/home/kl/.zshrc" ]; then
              mkdir -p "/home/kl/.config/zsh"
              cp /tmp/.zshrc /home/kl/.zshrc
              cp /tmp/.aliasrc /home/kl/.config/aliasrc
            fi

            if [ ! -d "/home/kl/.kl" ]; then
                  mkdir -p /home/kl/.kl
                  sh -c 'cat > /home/kl/.kl/kl-session.yaml <<EOF
                  session: sess-xtfmvde-xz1cj1osaobxeqkwsiyi
                  team: newteam
                  EOF'
            fi
          volumeMounts:
            - mountPath: /home/kl
              name: home-dir
            - mountPath: /nix
              name: nix-dir
            - mountPath: /env
              name: containerenv
        - name: envsetup
          image: ghcr.io/kloudlite/iac/workspace:latest
          env:
            - name: KL_WORKSPACE
              value: "workspaces/ws-name"
            - name: HOME
              value: "/home/kl"
          command:
          - "bash"
          - "-c"
          - |
            set -e
            if [[ -f /home/kl/$KL_WORKSPACE/kl.yaml || -f /home/kl/$KL_WORKSPACE/kl.yml ]]; then
              cd /home/kl/$KL_WORKSPACE
              runuser kl -c "PATH=$PATH:/home/kl/.nix-profile/bin /home/kl/.local/bin/kl shell -r >  /env/.env"
              runuser kl -c "PATH=$PATH:/home/kl/.nix-profile/bin /home/kl/.local/bin/kl shell -r"
            fi
          volumeMounts:
            - mountPath: /home/kl
              name: home-dir
            - mountPath: /nix
              name: nix-dir
            - mountPath: /env
              name: containerenv
      
      containers:
      - name: ssh
        image: ghcr.io/kloudlite/iac/workspace:latest
        imagePullPolicy: Always
        env:
          - name: KL_WORKSPACE
            value: "workspaces/ws-name"
        ports:
        - containerPort: 22
        command:
          - bash
          - -c
          - |
            set -e
            cat /env/.env >> /etc/environment
            echo "HOST=box" >> /etc/environment
            echo "KL_WORKSPACE=$(KL_WORKSPACE)" >> /etc/environment
            env sshd -D
        volumeMounts:
        - mountPath: /home/kl
          name: home-dir
        - mountPath: /nix
          name: nix-dir
        - mountPath: /env
          name: containerenv
      # - name: busybox
      #   image: ghcr.io/abdheshnayak/box:v1.0.0
      #   command: ["sleep", "3600"]
      #   volumeMounts:
      #     - mountPath: /home/kl
      #       name: home-dir
      #   command:
      #     - bash
      #     - -c
      #     - |
      #       /start.sh
      #       source /home/kl/.profile
      #       sudo sh -c 'cat > /home/kl/.kl/kl-extra-data.yaml <<EOF
      #       baseUrl: https://auth.kloudlite.io
      #       dnsHostSuffix: khost.dev
      #       lastUpdateCheck: "2025-02-05T12:18:24.071075127+05:30"
      #       backupDns: []
      #       EOF'
      #       sshd -D
        # securityContext:
        #   runAsUser: 1000
        #   runAsGroup: 1000
      #- name: jupyter
      #  image: ghcr.io/kloudlite/iac/jupyter:latest
      #  imagePullPolicy: Always
      #  ports:
      #  - containerPort: 8888
      #  volumeMounts:
      #    - mountPath: /home/kl
      #      name: home-dir
      #  securityContext:
      #    runAsUser: 1001
      #    runAsGroup: 1001
      #- name: vscode-server
      #  image: ghcr.io/kloudlite/iac/vscode-server:latest
      #  imagePullPolicy: Always
      #  volumeMounts:
      #    - mountPath: /home/kl
      #      name: home-dir
      #  securityContext:
      #    runAsUser: 1001
      #    runAsGroup: 1001
      #- name: code-server
      #  image: ghcr.io/kloudlite/iac/code-server:latest
      #  imagePullPolicy: Always
      #  volumeMounts:
      #    - mountPath: /home/kl
      #      name: home-dir
      #  securityContext:
      #    runAsUser: 1001
      #    runAsGroup: 1001

      volumes:
      - name: containerenv
        emptyDir: {}
      - name: home-dir
        hostPath:
          path: /var/user-home/
      - name: nix-dir
        hostPath:
          path: /var/nix-dir/