apiVersion: v1
kind: Service
metadata:
  name: exposed-services
spec:
  selector:
    app: code-web-service
  ports:
  - port: 2222
    targetPort: 22

---

apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
spec:
  selector:
    app: code-web-service
  ports:
  - port: 8888
    targetPort: 8888