name: build-docker-images

on:
  push:
    branches:
      - master
    paths:
      - "infrastructures/**/**"
      - "infrastructure/*"
      - "terraform/**"
      - ".github/workflows/**"
      - "cmd/*"

permissions:
  contents: read
  packages: write

jobs:
  docker-builds:
    strategy:
      matrix:
        name:
          - aws-spot-k3s-terminator
          - k3s-runner
          - infrastructures-as-code
        include:
          - name: aws-spot-k3s-terminator
            buildDir: cmd/aws-spot-k3s-terminator
          - name: k3s-runner
            buildDir: cmd/k3s-runner
          - name: iac
            buildDir: ./
    runs-on: ubuntu-latest
    name: Deploy to Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Install UPX
        run: |
          curl -L0 https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-amd64_linux.tar.xz > upx.tar.xz
          tar -xf upx.tar.xz
          sudo mv upx-4.2.1-amd64_linux/upx /usr/local/bin

      - name: Build Binary
        run: |
          task build Out=$PWD/.github/workflows/container-build/app CWD=${{matrix.buildDir}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image
        if: startsWith(github.ref, 'refs/heads/release')
        run: |

          branch_name=${GITHUB_REF#refs/heads/}
          version_string="v${branch_name#release-}-nightly"
          
          cd .github/workflows/container-build
          
          upx ./app
          task go-container-build --build-arg . -t ghcr.io/kloudlite/infrastructure-as-code/${{matrix.name}}:$version_string --push
          task go-container-build --build-arg . -t ghcr.io/kloudlite/infrastructure-as-code/${{matrix.name}}:commit-${GITHUB_SHA} --push